#!/bin/bash

source tomatoconfig

if test -f "$TOMATOPATH/$LOGFILE"
then
    echo "$LOGFILE"
    echo "----------"
    cat "$TOMATOPATH/$LOGFILE"
    echo
else
    echo "No tomatoes yet for $LOGFILE"
    echo
fi
